### ISSUE TITLE
Versatiles Frontend Docker Container Crashes Immediately on Startup

### ISSUE THREAD

**Issue by FabianRechsteiner** [versatiles-org/versatiles-docker#12]
Hello,

I attempted to start the Docker image versatiles/versatiles-frontend:v0.12.6 using Docker Compose. Unfortunately, it crashes immediately and stops.

Here is the compose.yaml file:

```yaml
---
services:
  versatiles:
    image: versatiles/versatiles-frontend:v0.12.6 # https://hub.docker.com/r/versatiles/versatiles-frontend
    container_name: versatiles
    volumes:
      - ./app:/app
    ports:
     - 8100:8080
    # restart: always
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    external: true
```

What is wrong with this configuration?

**Comment by MichaelKreil** [comment]
The current Docker images contain the `versatiles` binary and the frontend assets, but they do not execute anything by default. I haven't defined a `CMD` or `ENTRYPOINT` yet because I'm still considering the best approach to handle different map sources. 

At the moment, the container requires you to specify a command manually. (Also, note that if you mount the `/app` directory, it will overwrite the `versatiles` binary and `frontend.br.tar` that are included in the image.)

Here is an example of how you can manually define the command in your `docker-compose.yaml` to run the `versatiles` server:

```yaml
services:
  versatiles:
    image: versatiles/versatiles-frontend:alpine
    volumes:
      - ../tiles/:/data
    command: versatiles serve -s frontend.br.tar /data/osm.versatiles
```

But as I said, I would be very happy about suggestions or improvements regarding the setup of the Docker containers or the documentation.
